version: '3.9'
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - EXAMPLE_OF_ARG
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
    ports:
      - 8881:8000
    restart: unless-stopped